### ISSUE TITLE
non-existent service idci_step.navigator.factory

### ISSUE THREAD

**Issue by Barbarians** [IDCI-Consulting/StepBundle#46]
I upgrade my manager on sf3.4 but with your tag v3.1.4 I have this message

![image](https://user-images.githubusercontent.com/15941539/69163269-366f9d00-0aee-11ea-9b9d-67a2d16454b5.png)

https://github.com/IDCI-Consulting/StepBundle/blob/2.2/Resources/config/services.yml#L130-L138

https://github.com/IDCI-Consulting/StepBundle/blob/3.1/Resources/config/services.yml#L88-L89

**Comment by burahimu** [comment]
Is the service available with the `debug:container` command ?

If not, try using the [autowiring](https://symfony.com/doc/3.4/service_container/autowiring.html) by passing directly the `IDCI\Bundle\StepBundle\Navigation\NavigatorFactoryInterface` class in your controller action or service's contructor

**Comment by Barbarians** [comment]
It's ok for me, thanks for your reply
