### ISSUE TITLE
Removing attribute v2.2 => v3.0

### ISSUE THREAD

**Issue by Barbarians** [IDCI-Consulting/StepBundle#47]
Hi i have a problem with the css. 
i up version 2.2 to 3.0.
If i click on "generate the diagram of the map from the json" and my json is not valid, the modal-footer cut my button

![image](https://user-images.githubusercontent.com/15941539/74855114-886bcd00-5340-11ea-8da3-1e674ca2b938.png)

i have compare the version 2.2 and 3.0 and i see a change css on step-editore.vue the modla-footer is not in position relative but fixed.

https://github.com/IDCI-Consulting/StepBundle/blob/02780163255af3ede6662fecb1322be4cfbd16ad/Resources/public/js/editor/src/components/step-editor/step-editor.vue#L205

I think you have miss to change the position attribute on editor-common.css on v3.0 for have the same thing

https://github.com/IDCI-Consulting/ExtraFormBundle/blob/1e790385705f8d2eb02bc7bfeea05b0dc6c29c5b/Resources/public/js/editor/src/styles/editor-common.css#L127

**Comment by burahimu** [comment]
Hello @Barbarians,

Thanks for your feedback. Can you make a PR in this way :pray: ?

**Comment by Barbarians** [comment]
Check the PR https://github.com/IDCI-Consulting/ExtraFormBundle/pull/38 for fix this
